AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create EventBridge rule for scheduling
Resources:
  DailyAppointmentReminderRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: DailyAppointmentReminderRule
      ScheduleExpression: 'cron(0 22 * * ? *)'
      State: 'ENABLED'
      Targets:
        - Arn: arn:aws:lambda:us-east-1:137387558344:function:Reminder
          Id: 'ReminderFunction'
Outputs:
  ScheduleRuleArn:
    Description: ARN of the schedule EventBridge rule
    Value: !GetAtt DailyAppointmentReminderRule.Arn
