AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create SNS topic
Resources:
  PatientsNotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: PatientsNotification
Outputs:
  TopicArn:
    Description: ARN of the SNS topic
    Value: !Ref PatientsNotificationTopic
