apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-container
        image: us-central1-docker.pkg.dev/cloud-assignments-428917/k8-assignment/app1:latest
        volumeMounts:
        - mountPath: /Anjali_PV_dir
          name: standard-volume
      volumes:
      - name: standard-volume
        persistentVolumeClaim:
          claimName: standard-pvc